### ISSUE TITLE
Code Release 

### ISSUE THREAD

**Issue by abhigoku10** [yunlu-chen/PointMixup#1]
@yunlu-chen  thanks for ur work , what is the timeline for releasing your code !!!!!!!!!!!

**Comment by yunlu-chen** [comment]
> @yunlu-chen thanks for ur work , what is the timeline for releasing your code !!!!!!!!!!!

@abhigoku10 Thanks for your attention! 
Sorry to be late. The code will be released in late November.

**Comment by memoiry** [comment]
@yunlu-chen Hi, is there any update?

**Comment by zyoungDL** [comment]
Hi, today is Oct 27, I am looking forward to your code.

**Comment by yunlu-chen** [comment]
Thanks for your interest. We have released the code.
