### ISSUE TITLE
ModelNet40 version

### ISSUE THREAD

**Issue by antoalli** [yunlu-chen/PointMixup#3]
Hi! From my paper understanding you use two different versions of ModelNet40, one pre-aligned in experiments with DGCNN and the other un-aligned for PointNet++ experiments. Can you kindly point me to the specific versions used in your experimental setting (downloading links maybe)?
Thanks

**Comment by yunlu-chen** [comment]
The data is the same as all public versions of ModerNet40, but with unaligned version we do random rotation along up-axis for training and testing data.
